policy:
  amount-based:
    enabled: true
    # Defined as sorted map of [amount: discount in decimal fraction form]
    # e.g. 10: 0.25 means a 25,00% discount for 10+ products
    discounts:
      1000: 1.0
      20: 0.509
      10: 0.25
      5: 0.15
      3: 0.05
  percentage-based:
    enabled: true
    discount: 0.10