policy:
  amount-based:
    enabled: true
    # Defined as sorted map of [amount: discount in decimal fraction form]
    # e.g. 10: 0.25 means a 25,00% discount for 10+ products
    discounts:
      1000: 1.0
      20: 0.30
      10: 0.20
      5: 0.10
      3: 0.05
  percentage-based:
    enabled: true
    discount: 0.10

spring:
  data:
    mongodb:
      database: shopping-platform
      username: inpost
      password: inpost
      uuid-representation: standard