### Get a discount for an iPhone
GET http://localhost:8080/calculate-price-discount?productId=e737b48b-1fe2-476a-ba2e-85c44f036e86&amount=1

### Get a bulk discount for ASUS Zenfone 9
GET http://localhost:8080/calculate-price-discount?productId=09716a47-ab35-4753-8f12-b52e0f9ceca2&amount=50