version: "3.9"
services:
  mongo:
    build: ./mongo
    image: ${DOCKER_IMAGE_MONGO}
    restart: always
    ports:
      - "27017:27017"
    environment:
      # overwrite the image env when needed
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: shopping-platform
      MONGO_INITDB_USERNAME: inpost
      MONGO_INITDB_PASSWORD: inpost

  shopping-platform:
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo